# Generated by Django 5.2.3 on 2025-06-20 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('payment_for', models.CharField(choices=[('Electricity', 'Electricity'), ('Security', 'Security'), ('Development Levies', 'Development Levies'), ('Sanitations', 'Sanitations'), ('Others', 'Others')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cda', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='unpaid', max_length=20)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Regular Levies',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
