# Generated by Django 5.2.3 on 2025-06-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_approval_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
