# Generated by Django 5.2.1 on 2025-06-15 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0002_communityinfo_event_executivemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemember',
            name='cda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cda_app.cda'),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='executive_members/'),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
