# Generated by Django 5.2.3 on 2025-06-20 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0002_regularlevy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlevy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
