# Generated by Django 5.2.3 on 2025-06-26 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0003_approvallog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Approval Email Log', 'verbose_name_plural': 'Approval Email Logs'},
        ),
        migrations.RemoveField(
            model_name='approvallog',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='approvallog',
            name='email_sent_to',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvallog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
