# Generated by Django 5.2.3 on 2025-06-20 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0003_alter_regularlevy_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularlevy',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Regular Levy', 'verbose_name_plural': 'Regular Levies'},
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount to be paid', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='cda',
            field=models.CharField(help_text='Community Development Association', max_length=100, verbose_name='CDA'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select the month for this levy', max_length=20, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='payment_for',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Security', 'Security'), ('Development Levies', 'Development Levies'), ('Sanitations', 'Sanitations'), ('Others', 'Others')], help_text='Select the purpose of this payment', max_length=50, verbose_name='Payment For'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='proof_of_payment',
            field=models.ImageField(blank=True, help_text='Upload proof of payment', null=True, upload_to='payment_proofs/', verbose_name='Proof of Payment'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='unpaid', help_text='Current payment status', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levies', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='year',
            field=models.PositiveIntegerField(help_text='Enter the year for this levy', verbose_name='Year'),
        ),
        migrations.AddConstraint(
            model_name='regularlevy',
            constraint=models.UniqueConstraint(fields=('user', 'month', 'year', 'payment_for'), name='unique_user_levy_per_month'),
        ),
    ]
