# Generated by Django 5.2.1 on 2025-06-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0003_executivemember_cda_executivemember_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaulter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cda', models.CharField(max_length=100, verbose_name='CDA it belongs')),
                ('amount_indebted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title_defaulted', models.CharField(max_length=200, verbose_name="Title of what's defaulted")),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress')], default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
