# Generated by Django 5.2.3 on 2025-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0004_alter_regularlevy_options_alter_regularlevy_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlevy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='regularlevy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
