# Generated by Django 5.2.1 on 2025-06-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0004_defaulter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulter',
            name='cda',
            field=models.CharField(choices=[('Unity CDA', 'Unity CDA'), ('Harmony CDA', 'Harmony CDA'), ('Valley-View CDA', 'Valley-View CDA')], max_length=100, verbose_name='CDA'),
        ),
        migrations.AlterField(
            model_name='defaulter',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress'), ('Indebt', 'Indebt')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='defaulter',
            name='title_defaulted',
            field=models.CharField(choices=[('Security Fees', 'Security Fees'), ('Electricity', 'Electricity'), ('Development Levy', 'Development Levy'), ('Others', 'Others')], max_length=200, verbose_name='Debt For:'),
        ),
    ]
