# Generated by Django 5.2.3 on 2025-06-26 17:12

from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field

class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0004_alter_approvallog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinfo',
            name='content',
            field=CKEditor5Field(config_name='default'),
        ),
        migrations.AlterField(
            model_name='projectdonationmodal',
            name='content',
            field=CKEditor5Field(config_name='default'),
        ),
    ]
