# Generated by Django 5.2.3 on 2025-06-20 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0005_alter_regularlevy_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlevy',
            name='proof_of_payment',
            field=models.ImageField(blank=True, help_text='Upload proof of payment', null=True, upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Proof of Payment'),
        ),
    ]
