# Generated by Django 5.2.1 on 2025-06-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0005_alter_defaulter_cda_alter_defaulter_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='navbar_images/')),
                ('position', models.CharField(choices=[('left', 'Left Corner'), ('right', 'Right Corner')], max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
