# Generated by Django 5.2.3 on 2025-06-26 22:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0005_alter_communityinfo_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
