# Generated by Django 5.2.1 on 2025-06-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0006_navbarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='defaulter_images/'),
        ),
    ]
