# Generated by Django 5.2.3 on 2025-06-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0006_alter_regularlevy_proof_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDonationModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Donation Modal',
                'verbose_name_plural': 'Project Donation Modals',
            },
        ),
    ]
