# Generated by Django 5.2.3 on 2025-06-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0007_projectdonationmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdonationmodal',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdonationmodal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_modal_images/'),
        ),
    ]
