# Generated by Django 5.2.1 on 2025-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0008_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='paid_member_images/')),
                ('name', models.CharField(max_length=100)),
                ('cda', models.CharField(choices=[('Unity CDA', 'Unity CDA'), ('Harmony CDA', 'Harmony CDA'), ('Valley-View CDA', 'Valley-View CDA')], max_length=100, verbose_name='CDA')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose_of_payment', models.CharField(choices=[('Security Fees', 'Security Fees'), ('Electricity', 'Electricity'), ('Development Levy', 'Development Levy'), ('Others', 'Others')], max_length=200, verbose_name='Purpose of Payment')),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
