# Generated by Django 5.2.3 on 2025-06-28 19:43

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0008_communitypolicy_alter_birthdaycelebrant_admin_wishes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisan',
            options={'ordering': ['name'], 'verbose_name': 'Artisan', 'verbose_name_plural': 'Artisans'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['name'], 'verbose_name': 'Professional', 'verbose_name_plural': 'Professionals'},
        ),
        migrations.AddField(
            model_name='artisan',
            name='business_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='A brief description of their business.', null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for business inquiries.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or service area.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='num_reviews',
            field=models.IntegerField(default=0, help_text='Total number of reviews received.'),
        ),
        migrations.AddField(
            model_name='artisan',
            name='products_services',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed list of products/services offered.', null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating based on reviews (e.g., 4.5).', max_digits=3),
        ),
        migrations.AddField(
            model_name='artisan',
            name='working_hours',
            field=models.CharField(blank=True, help_text='e.g., Mon-Fri: 9 AM - 5 PM, Sat: 10 AM - 2 PM.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='business_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='A brief description of their professional service.', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for business inquiries.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or service area.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='num_reviews',
            field=models.IntegerField(default=0, help_text='Total number of reviews received.'),
        ),
        migrations.AddField(
            model_name='professional',
            name='products_services',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed list of services offered.', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating based on reviews (e.g., 4.8).', max_digits=3),
        ),
        migrations.AddField(
            model_name='professional',
            name='working_hours',
            field=models.CharField(blank=True, help_text='e.g., Mon-Fri: 9 AM - 5 PM.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a main profile picture for the artisan.', null=True, upload_to='artisans/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='job_title',
            field=models.CharField(help_text='e.g., Plumber, Electrician, Carpenter.', max_length=100),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='name',
            field=models.CharField(help_text='Full name of the artisan.', max_length=100),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number for contact.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a main profile picture for the professional.', null=True, upload_to='professionals/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='job_title',
            field=models.CharField(help_text='e.g., Accountant, Lawyer, Architect.', max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(help_text='Full name of the professional.', max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number for contact.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ArtisanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Upload an image for the artisan's gallery.", upload_to='artisan_galleries/')),
                ('description', models.CharField(blank=True, help_text='Optional description for the image.', max_length=255, null=True)),
                ('artisan', models.ForeignKey(help_text='The artisan this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cda_app.artisan')),
            ],
            options={
                'verbose_name': 'Artisan Gallery Image',
                'verbose_name_plural': 'Artisan Gallery Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Upload an image for the professional's gallery.", upload_to='professional_galleries/')),
                ('description', models.CharField(blank=True, help_text='Optional description for the image.', max_length=255, null=True)),
                ('professional', models.ForeignKey(help_text='The professional this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cda_app.professional')),
            ],
            options={
                'verbose_name': 'Professional Gallery Image',
                'verbose_name_plural': 'Professional Gallery Images',
                'ordering': ['id'],
            },
        ),
    ]
