# Generated by Django 5.2.3 on 2025-06-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0008_projectdonationmodal_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayCelebrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='celebrant_images/')),
                ('date_of_birth', models.DateField()),
                ('admin_wishes', models.TextField()),
            ],
            options={
                'verbose_name': 'Birthday Celebrant',
                'verbose_name_plural': 'Birthday Celebrants',
            },
        ),
        migrations.AlterModelOptions(
            name='projectdonationmodal',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectdonationmodal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectdonationmodal',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='projectdonationmodal',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='projectdonationmodal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_donation_images/'),
        ),
    ]
