# Generated by Django 5.2.3 on 2025-06-24 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0009_birthdaycelebrant_alter_projectdonationmodal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellWishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celebrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_wishes', to='cda_app.birthdaycelebrant')),
            ],
            options={
                'verbose_name': 'Well Wish',
                'verbose_name_plural': 'Well Wishes',
                'ordering': ['-created_at'],
            },
        ),
    ]
