# Generated by Django 5.2.3 on 2025-06-24 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0010_wellwishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellWishReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cda_app.wellwishes')),
            ],
            options={
                'verbose_name_plural': 'Well Wish Replies',
                'ordering': ['-created_at'],
            },
        ),
    ]
