# Generated by Django 5.2.1 on 2025-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0011_advertcategory_advertitem_advertimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertitem',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
