# Generated by Django 5.2.1 on 2025-06-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0012_advertitem_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertitem',
            name='condition',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertitem',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AdvertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('willing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cda_app.advertitem')),
            ],
        ),
    ]
