# Generated by Django 5.2.1 on 2025-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0014_userprofile_image_userprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
